# Generated by Django 3.1.2 on 2020-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201010_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
