# Generated by Django 3.1.2 on 2020-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_order_rated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status']},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='on_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
