# Generated by Django 3.1.2 on 2020-10-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discount_price',
            new_name='pre_discount_price',
        ),
    ]
